/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.GerenciadorEspacos;
import controle.GerenciadorReservaEspaco;
import controle.GerenciadorUsuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Espaco;
import modelo.Evento;
import modelo.ReservaEspaco;
import modelo.Usuario;

/**
 *
 *
 */
public class TelaReservaEspaco extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaReservaEspaco
     */
    public TelaReservaEspaco() {
        initComponents();
        GerenciadorEspacos ge = GerenciadorEspacos.getInstance();
        ge.buscarEspaco("");
        ArrayList<Espaco> espacos = ge.getListaEspacos();
        for (int i = 0; i < espacos.size(); i++) {
            cbEspacoEvento.addItem(espacos.get(i).getDescEspaco());
        }
        GerenciadorUsuarios gr = GerenciadorUsuarios.getInstance();
        Usuario usuario = gr.getUsuarioLogado();
        tfRespResEsp.setText(usuario.getEmail());
        tfFoneResEsp.setText(usuario.getTelefone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDataEvt = new javax.swing.JFormattedTextField();
        lbDataEvt = new javax.swing.JLabel();
        tfHoraEvt = new javax.swing.JFormattedTextField();
        lbHoraEvt = new javax.swing.JLabel();
        btSalvarEvt = new javax.swing.JButton();
        btLimparEvt = new javax.swing.JButton();
        btExcluirEvt = new javax.swing.JButton();
        tfFoneEvt = new javax.swing.JFormattedTextField();
        lbFoneEvt = new javax.swing.JLabel();
        tfRespEvt = new javax.swing.JTextField();
        lbRespEvt = new javax.swing.JLabel();
        tfDescEsp = new javax.swing.JTextField();
        lbDescEsp = new javax.swing.JLabel();
        lbTituloTelaResEsp = new javax.swing.JLabel();
        tfDataResEsp = new javax.swing.JFormattedTextField();
        lbDataResEsp = new javax.swing.JLabel();
        tfHoraResEsp = new javax.swing.JFormattedTextField();
        lbHoraResEsp = new javax.swing.JLabel();
        btSalvarResEsp = new javax.swing.JButton();
        btLimparResEsp = new javax.swing.JButton();
        btExcluirResEsp = new javax.swing.JButton();
        tfFoneResEsp = new javax.swing.JFormattedTextField();
        lbFoneResEsp = new javax.swing.JLabel();
        tfRespResEsp = new javax.swing.JTextField();
        lbRespResEsp = new javax.swing.JLabel();
        cbEspacoEvento = new javax.swing.JComboBox<>();
        lbDescEsp1 = new javax.swing.JLabel();

        try {
            tfDataEvt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbDataEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataEvt.setText("Data");

        try {
            tfHoraEvt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfHoraEvt.setText("");
        tfHoraEvt.setToolTipText("");
        tfHoraEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoraEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHoraEvt.setText("Hora");

        btSalvarEvt.setBackground(new java.awt.Color(50, 150, 0));
        btSalvarEvt.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btSalvarEvt.setText("Salvar");
        btSalvarEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarEvtActionPerformed(evt);
            }
        });

        btLimparEvt.setBackground(new java.awt.Color(255, 153, 0));
        btLimparEvt.setForeground(new java.awt.Color(255, 255, 255));
        btLimparEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh-24_1.png"))); // NOI18N
        btLimparEvt.setText("Limpar");
        btLimparEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparEvtActionPerformed(evt);
            }
        });

        btExcluirEvt.setBackground(new java.awt.Color(255, 0, 0));
        btExcluirEvt.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btExcluirEvt.setText("Excluir");
        btExcluirEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirEvtActionPerformed(evt);
            }
        });

        try {
            tfFoneEvt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfFoneEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFoneEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFoneEvtActionPerformed(evt);
            }
        });

        lbFoneEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFoneEvt.setText("Fone");

        tfRespEvt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbRespEvt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRespEvt.setText("Responsável");

        setClosable(true);

        tfDescEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbDescEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescEsp.setText("Descrição");

        lbTituloTelaResEsp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTituloTelaResEsp.setText("Reserva espaço");

        try {
            tfDataResEsp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataResEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbDataResEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataResEsp.setText("Data");

        try {
            tfHoraResEsp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfHoraResEsp.setText("");
        tfHoraResEsp.setToolTipText("");
        tfHoraResEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoraResEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHoraResEsp.setText("Hora");

        btSalvarResEsp.setBackground(new java.awt.Color(50, 150, 0));
        btSalvarResEsp.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarResEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btSalvarResEsp.setText("Reservar");
        btSalvarResEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarResEspActionPerformed(evt);
            }
        });

        btLimparResEsp.setBackground(new java.awt.Color(255, 153, 0));
        btLimparResEsp.setForeground(new java.awt.Color(255, 255, 255));
        btLimparResEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh-24_1.png"))); // NOI18N
        btLimparResEsp.setText("Limpar");
        btLimparResEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparResEspActionPerformed(evt);
            }
        });

        btExcluirResEsp.setBackground(new java.awt.Color(255, 0, 0));
        btExcluirResEsp.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirResEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btExcluirResEsp.setText("Excluir");
        btExcluirResEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirResEspActionPerformed(evt);
            }
        });

        tfFoneResEsp.setEditable(false);
        try {
            tfFoneResEsp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfFoneResEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFoneResEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFoneResEspActionPerformed(evt);
            }
        });

        lbFoneResEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFoneResEsp.setText("Fone");

        tfRespResEsp.setEditable(false);
        tfRespResEsp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbRespResEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRespResEsp.setText("Responsável");

        lbDescEsp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescEsp1.setText("Espaço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescEsp)
                            .addComponent(lbDescEsp1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbEspacoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbHoraResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfHoraResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfDescEsp, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btSalvarResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTituloTelaResEsp)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbDataResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfDataResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimparResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btExcluirResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbRespResEsp)
                        .addComponent(lbFoneResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfFoneResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfRespResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTituloTelaResEsp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspacoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescEsp1))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescEsp)
                    .addComponent(tfDescEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataResEsp)
                    .addComponent(tfDataResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoraResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHoraResEsp, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarResEsp)
                    .addComponent(btLimparResEsp)
                    .addComponent(btExcluirResEsp))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(119, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbRespResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfRespResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbFoneResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfFoneResEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(208, 208, 208)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarEvtActionPerformed


    }//GEN-LAST:event_btSalvarEvtActionPerformed

    private void btLimparEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparEvtActionPerformed

    }//GEN-LAST:event_btLimparEvtActionPerformed

    private void btExcluirEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirEvtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btExcluirEvtActionPerformed

    private void tfFoneEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFoneEvtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFoneEvtActionPerformed

    private void btSalvarResEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarResEspActionPerformed

        String espacodesc = cbEspacoEvento.getSelectedItem().toString();
        if (espacodesc.equals("")) {
            JOptionPane.showMessageDialog(null, "Espaço não selecionado");
            return;
        }
        String data = tfDataResEsp.getText();
        if (data.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo data está vazio");
            return;
        }
        String descricao = tfDescEsp.getText();
        if (descricao.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo descricão está vazio");
            return;
        }
        String hora = tfHoraResEsp.getText();
        if (hora.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo hora está vazio");
            return;
        }

        GerenciadorUsuarios gr = GerenciadorUsuarios.getInstance();
        Usuario usuariologado = gr.getUsuarioLogado();
        GerenciadorEspacos ge = GerenciadorEspacos.getInstance();
        Espaco espaco = ge.buscarEspaco(espacodesc);
        
        GerenciadorReservaEspaco gre = GerenciadorReservaEspaco.getInstance();
        
        boolean reservado = gre.AdicionarReserva(usuariologado, espaco, data, hora);
        if(reservado == true) {
            JOptionPane.showMessageDialog(null, "Espaço reservado com sucesso!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Já existe reserva neste espaço, para a data e hora indicadas");
        }

        cbEspacoEvento.setSelectedItem("");
        tfDataResEsp.setText("");
        tfHoraResEsp.setText("");
        tfDescEsp.setText("");

    }//GEN-LAST:event_btSalvarResEspActionPerformed

    private void btLimparResEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparResEspActionPerformed

        cbEspacoEvento.setSelectedItem("");
        tfDataResEsp.setText("");
        tfHoraResEsp.setText("");
        tfDescEsp.setText("");
    }//GEN-LAST:event_btLimparResEspActionPerformed

    private void btExcluirResEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirResEspActionPerformed

        JOptionPane.showMessageDialog(null, "Reserva de espaço excluída com sucesso!");
        cbEspacoEvento.setSelectedItem("");
        tfFoneResEsp.setText("");
        tfDataResEsp.setText("");
        tfRespResEsp.setText("");
        tfHoraResEsp.setText("");
        tfDescEsp.setText("");
    }//GEN-LAST:event_btExcluirResEspActionPerformed

    private void tfFoneResEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFoneResEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFoneResEspActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluirEvt;
    private javax.swing.JButton btExcluirResEsp;
    private javax.swing.JButton btLimparEvt;
    private javax.swing.JButton btLimparResEsp;
    private javax.swing.JButton btSalvarEvt;
    private javax.swing.JButton btSalvarResEsp;
    private javax.swing.JComboBox<String> cbEspacoEvento;
    private javax.swing.JLabel lbDataEvt;
    private javax.swing.JLabel lbDataResEsp;
    private javax.swing.JLabel lbDescEsp;
    private javax.swing.JLabel lbDescEsp1;
    private javax.swing.JLabel lbFoneEvt;
    private javax.swing.JLabel lbFoneResEsp;
    private javax.swing.JLabel lbHoraEvt;
    private javax.swing.JLabel lbHoraResEsp;
    private javax.swing.JLabel lbRespEvt;
    private javax.swing.JLabel lbRespResEsp;
    private javax.swing.JLabel lbTituloTelaResEsp;
    private javax.swing.JFormattedTextField tfDataEvt;
    private javax.swing.JFormattedTextField tfDataResEsp;
    private javax.swing.JTextField tfDescEsp;
    private javax.swing.JFormattedTextField tfFoneEvt;
    private javax.swing.JFormattedTextField tfFoneResEsp;
    private javax.swing.JFormattedTextField tfHoraEvt;
    private javax.swing.JFormattedTextField tfHoraResEsp;
    private javax.swing.JTextField tfRespEvt;
    private javax.swing.JTextField tfRespResEsp;
    // End of variables declaration//GEN-END:variables
}
