/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.GerenciadorUsuarios;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author ruand
 */
public class TelaCadastroUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroUsuarioPanel
     */
    public TelaCadastroUsuarioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBotoes = new javax.swing.JPanel();
        btExcluirUsu = new javax.swing.JButton();
        btLimparUsu = new javax.swing.JButton();
        btSalvarUsu = new javax.swing.JButton();
        lbTituloCadastroUsu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbEnderecoUsu = new javax.swing.JLabel();
        jRStatusUsu = new javax.swing.JRadioButton();
        tfCPFUsu = new javax.swing.JTextField();
        jRStatusInaUsu = new javax.swing.JRadioButton();
        tfNomeUsu = new javax.swing.JTextField();
        tfEmailUsu = new javax.swing.JTextField();
        tfEndUsu = new javax.swing.JTextField();
        btBuscarUsu = new javax.swing.JButton();
        lbDataNascUsu = new javax.swing.JLabel();
        tfDataNascUsu = new javax.swing.JTextField();
        lbSenhaoUsu = new javax.swing.JLabel();
        lbCidadeUsu = new javax.swing.JLabel();
        lbBairroUsu = new javax.swing.JLabel();
        tfFoneUsu = new javax.swing.JTextField();
        lbFoneUsu = new javax.swing.JLabel();
        tfCidadeUsu = new javax.swing.JTextField();
        lbNomeUsu = new javax.swing.JLabel();
        tfSenhaUsu = new javax.swing.JTextField();
        lbEmailUsu = new javax.swing.JLabel();
        tfBairroUsu = new javax.swing.JTextField();
        lbCPFUsu = new javax.swing.JLabel();
        lbStatusUsu = new javax.swing.JLabel();
        lbTipoUsu = new javax.swing.JLabel();
        jCtipoUsu = new javax.swing.JComboBox<>();

        btExcluirUsu.setBackground(new java.awt.Color(255, 0, 0));
        btExcluirUsu.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-24_1.png"))); // NOI18N
        btExcluirUsu.setText("Excluir");

        btLimparUsu.setBackground(new java.awt.Color(255, 153, 0));
        btLimparUsu.setForeground(new java.awt.Color(255, 255, 255));
        btLimparUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh-24_1.png"))); // NOI18N
        btLimparUsu.setText("Limpar");
        btLimparUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparUsuActionPerformed(evt);
            }
        });

        btSalvarUsu.setBackground(new java.awt.Color(50, 150, 0));
        btSalvarUsu.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save-24_1.png"))); // NOI18N
        btSalvarUsu.setText("Salvar");
        btSalvarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotoesLayout = new javax.swing.GroupLayout(jPBotoes);
        jPBotoes.setLayout(jPBotoesLayout);
        jPBotoesLayout.setHorizontalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btSalvarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btLimparUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btExcluirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPBotoesLayout.setVerticalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarUsu)
                    .addComponent(btLimparUsu)
                    .addComponent(btExcluirUsu))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lbTituloCadastroUsu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTituloCadastroUsu.setText("Cadastro de Usuarios");

        lbEnderecoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEnderecoUsu.setText("Endereço:");

        jRStatusUsu.setText("Ativo");

        tfCPFUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jRStatusInaUsu.setText("Inativo");

        tfNomeUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNomeUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeUsuActionPerformed(evt);
            }
        });

        tfEmailUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfEmailUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailUsuActionPerformed(evt);
            }
        });

        tfEndUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btBuscarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search-12-16_1.png"))); // NOI18N
        btBuscarUsu.setPreferredSize(new java.awt.Dimension(23, 23));
        btBuscarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarUsuActionPerformed(evt);
            }
        });

        lbDataNascUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataNascUsu.setText("Data de nascimento:");

        tfDataNascUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbSenhaoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSenhaoUsu.setText("Senha:");

        lbCidadeUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCidadeUsu.setText("Cidade:");

        lbBairroUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbBairroUsu.setText("Bairro:");

        tfFoneUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbFoneUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFoneUsu.setText("Fone:");

        tfCidadeUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbNomeUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeUsu.setText("Nome:");

        tfSenhaUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSenhaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaUsuActionPerformed(evt);
            }
        });

        lbEmailUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEmailUsu.setText("E-mail:");

        tfBairroUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbCPFUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCPFUsu.setText("CPF:");

        lbStatusUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbStatusUsu.setText("Status:");

        lbTipoUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTipoUsu.setText("Tipo:");

        jCtipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Funcionario", "Externo", " " }));
        jCtipoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSenhaoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbBairroUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNomeUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEmailUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCPFUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEnderecoUsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbFoneUsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfEmailUsu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tfNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfEndUsu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfSenhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBairroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbCidadeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfCidadeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbStatusUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRStatusUsu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRStatusInaUsu)
                                        .addGap(13, 13, 13))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCPFUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbDataNascUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDataNascUsu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfFoneUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbTipoUsu)
                                .addGap(41, 41, 41)
                                .addComponent(jCtipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPFUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCPFUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataNascUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataNascUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFoneUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFoneUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCtipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEndUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCidadeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCidadeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBairroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenhaoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSenhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStatusUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRStatusUsu)
                    .addComponent(jRStatusInaUsu))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbTituloCadastroUsu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lbTituloCadastroUsu)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparUsuActionPerformed

    private void btSalvarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarUsuActionPerformed
        // TODO add your handling code here:
        String nome = tfNomeUsu.getText();
        if(nome.length() == 0) {
            JOptionPane.showMessageDialog(null,"Esqueceu de digitar o nome");
            return;
        }
        String email = tfEmailUsu.getText();
        if (email.length()==0){
            JOptionPane.showMessageDialog(null, "Email em branco");
            return;
        }
        String cpf = tfCPFUsu.getText();
        if (cpf.length()==0){
            JOptionPane.showMessageDialog(null,"cpf em branco");
            return;
        }
        String fone = tfFoneUsu.getText();
        if(fone.length()==0){
            JOptionPane.showMessageDialog(null,"telefone em branco");
            return;
        }
        String endereco = tfEndUsu.getText();
        if(endereco.length()==0){
            JOptionPane.showMessageDialog(null,"Endereço vazio");
            return;
        }
        String bairro = tfBairroUsu.getText();
        if (bairro.length()==0){
            JOptionPane.showMessageDialog(null,"Campo bairro está vazio");
            return;
        }
        String senha = tfSenhaUsu.getText();
        if (senha.length()==0){
            JOptionPane.showMessageDialog(null,"Campo senha vazio");
            return;

        }
        String cidade = tfCidadeUsu.getText();
        if (cidade.length()==0){
            JOptionPane.showMessageDialog(null,"Campo cidade vazio");
            return;
        }
        String nascimento = tfDataNascUsu.getText();
        if (nascimento.length()==0){
            JOptionPane.showMessageDialog(null,"Campo data de nascimento vazio");
            return;
        }
        endereco += ", " + bairro + ", " + cidade;
        Usuario user = new Usuario(senha,nome,endereco,email,fone,nascimento,cpf);
        GerenciadorUsuarios gerenciadorUsu = GerenciadorUsuarios.getInstance();
        gerenciadorUsu.addUsuario(user);
        
    }//GEN-LAST:event_btSalvarUsuActionPerformed

    private void tfSenhaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSenhaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSenhaUsuActionPerformed

    private void jCtipoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtipoUsuActionPerformed

    private void tfNomeUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeUsuActionPerformed

    private void tfEmailUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailUsuActionPerformed

    private void btBuscarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarUsuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarUsu;
    private javax.swing.JButton btExcluirUsu;
    private javax.swing.JButton btLimparUsu;
    private javax.swing.JButton btSalvarUsu;
    private javax.swing.JComboBox<String> jCtipoUsu;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRStatusInaUsu;
    private javax.swing.JRadioButton jRStatusUsu;
    private javax.swing.JLabel lbBairroUsu;
    private javax.swing.JLabel lbCPFUsu;
    private javax.swing.JLabel lbCidadeUsu;
    private javax.swing.JLabel lbDataNascUsu;
    private javax.swing.JLabel lbEmailUsu;
    private javax.swing.JLabel lbEnderecoUsu;
    private javax.swing.JLabel lbFoneUsu;
    private javax.swing.JLabel lbNomeUsu;
    private javax.swing.JLabel lbSenhaoUsu;
    private javax.swing.JLabel lbStatusUsu;
    private javax.swing.JLabel lbTipoUsu;
    private javax.swing.JLabel lbTituloCadastroUsu;
    private javax.swing.JTextField tfBairroUsu;
    private javax.swing.JTextField tfCPFUsu;
    private javax.swing.JTextField tfCidadeUsu;
    private javax.swing.JTextField tfDataNascUsu;
    private javax.swing.JTextField tfEmailUsu;
    private javax.swing.JTextField tfEndUsu;
    private javax.swing.JTextField tfFoneUsu;
    private javax.swing.JTextField tfNomeUsu;
    private javax.swing.JTextField tfSenhaUsu;
    // End of variables declaration//GEN-END:variables
}
